Ecommerce_dbt_DQC:
  outputs:
    dev:
      dbname: "{{ env_var('PGDATABASE') }}"
      host: "{{ env_var('DB_HOST') }}"
      password: "{{ env_var('PGPASSWORD') }}"
      port: "{{ env_var('DB_PORT') | int }}"
      schema: "{{ env_var('PGSCHEMA') }}"
      threads: 1
      type: postgres
      user: "{{ env_var('PGUSER') }}"
    prod:
      dbname: "{{ env_var('PGDATABASE') }}"
      host: "{{ env_var('DB_HOST') }}"
      password: "{{ env_var('PGPASSWORD') }}"
      port: "{{ env_var('DB_PORT') | int }}"
      schema: "{{ env_var('PGSCHEMA') }}"
      threads: 1
      type: postgres
      user: "{{ env_var('PGUSER') }}"
  target: dev